import { useEffect, useMemo, useRef, useState, type PointerEvent as ReactPointerEvent } from "react";
import { ArrowRight, ArrowUpRight, AudioLines, Disc3, House, Instagram, Mail, Music2, Pause, Play, Share2, Sparkles, X } from "lucide-react";

type Beat = { id: string; title: string; styles: string[]; moods: string[]; bpm: number; previewUrl: string; accent: string; };

const beats: Beat[] = [
  { id: "noite", title: "Noite sem placa", styles: ["trap", "dark"], moods: ["madrugada", "grave pesado"], bpm: 142, previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3", accent: "beat-purple" },
  { id: "subsolo", title: "Subsolo 02", styles: ["drill", "trap"], moods: ["rua", "grave pesado"], bpm: 138, previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3", accent: "beat-orange" },
  { id: "ponto", title: "Ponto cego", styles: ["boom bap", "rap"], moods: ["madrugada", "confissão"], bpm: 92, previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3", accent: "beat-green" },
  { id: "sem-freio", title: "Sem freio", styles: ["trap", "funk"], moods: ["energia alta", "rua"], bpm: 150, previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3", accent: "beat-pink" },
];

const styles = ["todos", "trap", "drill", "boom bap", "rap", "funk"];
const moods = ["todos", "madrugada", "grave pesado", "rua", "melódico", "energia alta"];
const releases = [{ title: "Sinal de fumaça", artist: "Lia Nox", role: "produção · mix · master", year: "2024", color: "release-red" }, { title: "Afterglow", artist: "NINA / M", role: "produção · mix", year: "2023", color: "release-blue" }];

function Cover({ beat, className = "" }: { beat: Beat; className?: string }) { return <div className={`radio-cover ${beat.accent} ${className}`}><span className="cover-code">JA / {beat.id.slice(0, 3).toUpperCase()}</span><span className="cover-sun" /><span className="cover-title">{beat.title.split(" ").slice(0, 2).join(" ")}<br /><b>{beat.title.split(" ").slice(2).join(" ")}</b></span><span className="cover-bpm">{beat.bpm} BPM</span></div>; }
function Bars({ active = false }: { active?: boolean }) { return <span className={`radio-bars ${active ? "active" : ""}`}><i /><i /><i /><i /><i /></span>; }

export default function Home() {
  const audioRef = useRef<HTMLAudioElement | null>(null);
  const previewTimerRef = useRef<number | null>(null);
  const [activeId, setActiveId] = useState("noite");
  const [playing, setPlaying] = useState(false);
  const [styleFilter, setStyleFilter] = useState("todos");
  const [moodFilter, setMoodFilter] = useState("todos");
  const [progress, setProgress] = useState(0);
  const [signalMessage, setSignalMessage] = useState("sinal aberto / 24 horas");
  const [shared, setShared] = useState(false);
  const activeBeat = beats.find(b => b.id === activeId) ?? beats[0];
  const filteredBeats = useMemo(() => beats.filter(b => (styleFilter === "todos" || b.styles.includes(styleFilter)) && (moodFilter === "todos" || b.moods.includes(moodFilter))), [styleFilter, moodFilter]);

  useEffect(() => { const audio = new Audio(); audio.preload = "none"; audioRef.current = audio; const tick = () => setProgress(audio.duration ? audio.currentTime / audio.duration : 0); const end = () => { setPlaying(false); setProgress(0); }; audio.addEventListener("timeupdate", tick); audio.addEventListener("ended", end); return () => { audio.pause(); if (previewTimerRef.current) window.clearTimeout(previewTimerRef.current); audio.removeEventListener("timeupdate", tick); audio.removeEventListener("ended", end); }; }, []);
  useEffect(() => { const messages = ["sinal aberto / 24 horas", "nova escuta disponível", "grave circulando agora", "J.A está no ar"]; let index = 0; const timer = window.setInterval(() => { index = (index + 1) % messages.length; setSignalMessage(messages[index]); }, 4200); return () => window.clearInterval(timer); }, []);
  useEffect(() => { setSignalMessage(playing ? `tocando agora / ${activeBeat.title}` : `pronto para ouvir / ${activeBeat.title}`); }, [activeBeat.id, playing]);
  useEffect(() => { const shell = document.querySelector(".radio-shell"); const sections = document.querySelectorAll<HTMLElement>(".reveal-section"); if (!shell || !sections.length) return; shell.classList.add("reveal-ready"); const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add("is-visible"); observer.unobserve(entry.target); } }), { threshold: 0.12, rootMargin: "0px 0px -8% 0px" }); sections.forEach(section => observer.observe(section)); return () => observer.disconnect(); }, []);
  const clearPreviewTimer = () => { if (previewTimerRef.current) window.clearTimeout(previewTimerRef.current); previewTimerRef.current = null; };
  const stopBeatPreview = () => { clearPreviewTimer(); audioRef.current?.pause(); if (audioRef.current) audioRef.current.currentTime = 0; setPlaying(false); setProgress(0); };
  const playBeat = async (beat: Beat) => { const audio = audioRef.current; if (!audio) return; if (activeId === beat.id && playing) { stopBeatPreview(); return; } clearPreviewTimer(); audio.pause(); if (activeId !== beat.id) { audio.src = beat.previewUrl; setActiveId(beat.id); } setProgress(0); previewTimerRef.current = window.setTimeout(stopBeatPreview, 5000); try { await audio.play(); setPlaying(true); } catch { stopBeatPreview(); } };
  const handleCardPointerEnter = (event: ReactPointerEvent<HTMLButtonElement>, beat: Beat) => { if (event.pointerType === "mouse") void playBeat(beat); };
  const handleCardPointerLeave = (event: ReactPointerEvent<HTMLButtonElement>) => { if (event.pointerType === "mouse") stopBeatPreview(); };
  const handleCardPointerDown = (event: ReactPointerEvent<HTMLButtonElement>, beat: Beat) => { if (event.pointerType !== "mouse") { event.preventDefault(); void playBeat(beat); } };
  const shareBeat = async () => { const shareData = { title: `${activeBeat.title} — J.A Radio`, text: `Ouça ${activeBeat.title}, beat do J.A.`, url: window.location.href }; try { if (navigator.share) await navigator.share(shareData); else await navigator.clipboard.writeText(window.location.href); setShared(true); window.setTimeout(() => setShared(false), 2200); } catch { setShared(false); } };
  const selectStyle = (item: string) => { setStyleFilter(item); setSignalMessage(item === "todos" ? "todos os sons / J.A" : `frequência selecionada / ${item}`); };
  const selectMood = (item: string) => { setMoodFilter(item); setSignalMessage(item === "todos" ? "todos os climas / J.A" : `clima selecionado / ${item}`); };
  const contactHref = `mailto:contato@joaoalvarez.com?subject=${encodeURIComponent(`Quero criar em cima de ${activeBeat.title}`)}&body=${encodeURIComponent(`Fala, J.A. Ouvi o beat ${activeBeat.title} e queria conversar sobre uma ideia.`)}`;

  return <div className={`radio-shell ${playing ? "radio-is-playing" : ""}`}>
    <header className="radio-header"><a href="#top" className="radio-brand"><span className="ja-stamp">J.A</span><span><b>J.A RADIO</b><small>João Alvarez / beats & produção</small></span></a><nav><a href="/catalogo">catálogo</a><a href="#explore">explorar</a><a href="#releases">lançamentos</a><a href="#about">sobre</a></nav><a href={contactHref} className="radio-header-cta">mandar ideia <ArrowUpRight size={14} /></a></header>
    <main id="top">
      <section className="radio-hero radio-wrap reveal-section"><div className="hero-copy-radio"><div className="radio-kicker"><span className="live-dot" /> <span className="signal-copy" aria-live="polite">{signalMessage}</span></div><h1>Encontre<br />seu <em>som.</em></h1><p>Uma rádio de beats, ideias e músicas para quem está procurando o próximo grave.</p><a className="radio-button dark-button" href="#explore">Explorar beats <ArrowRight size={16} /></a></div><div className={`hero-signal-board ${playing ? "is-live" : ""}`}><div className="signal-board-top"><span>J.A / rádio urbana</span><span>{playing ? "ao vivo" : "stand by"}</span></div><div className="signal-orb"><div className="hero-disc"><Cover beat={activeBeat} className="hero-disc-cover" /><span className="hero-disc-hole" /></div></div><div className="signal-orb-status"><Bars active={playing} /><strong>{playing ? "grave em movimento" : "aperte play abaixo"}</strong><span>trap / rap / rua</span></div><div className="signal-board-bottom"><span>arquivo aberto</span><span>24 / 7</span><span>JA—013</span></div></div></section>
      <section id="explore" className="explore-section radio-wrap reveal-section"><div className="radio-section-head"><div><span className="section-no">01</span><h2>Escolha uma<br /><em>frequência.</em></h2></div><p>Não precisa saber o nome.<br />Só sentir o que combina.</p></div><div className="filter-block"><span>estilo</span><div className="filter-row">{styles.map(item => <button key={item} className={styleFilter === item ? "selected" : ""} onClick={() => selectStyle(item)}>{item}</button>)}</div><span>clima</span><div className="filter-row mood-row">{moods.map(item => <button key={item} className={moodFilter === item ? "selected" : ""} onClick={() => selectMood(item)}>{item}</button>)}</div></div><div className="catalog-head"><span>{filteredBeats.length.toString().padStart(2, "0")} beats encontrados</span><span><Sparkles size={13} /> curadoria J.A</span></div><div className="beat-grid">{filteredBeats.map(beat => <article className={`beat-card ${activeId === beat.id ? "selected-card" : ""}`} key={beat.id}><button onClick={(event) => { if (event.detail === 0 || window.matchMedia("(hover: hover)").matches) void playBeat(beat); }} onPointerEnter={(event) => handleCardPointerEnter(event, beat)} onPointerLeave={handleCardPointerLeave} onPointerDown={(event) => handleCardPointerDown(event, beat)} className="beat-art-button" aria-label={`Ouvir preview de ${beat.title}`}><Cover beat={beat} /><span className="beat-play">{activeId === beat.id && playing ? <Pause size={15} fill="currentColor" /> : <Play size={15} fill="currentColor" />}</span></button><div className="beat-card-info"><div><h3>{beat.title}</h3><p>{beat.styles.join(" / ")} · {beat.bpm} BPM</p></div><a href={`mailto:contato@joaoalvarez.com?subject=${encodeURIComponent(`Quero criar em cima de ${beat.title}`)}`} aria-label={`Quero criar em cima de ${beat.title}`}><ArrowUpRight size={16} /></a></div></article>)}</div>{filteredBeats.length === 0 && <div className="empty-state">Ainda não chegou esse grave.<br /><button onClick={() => { setStyleFilter("todos"); setMoodFilter("todos"); }}>limpar filtros <X size={13} /></button></div>}<div className="briefing-strip"><div><span className="section-no">02</span><h2>Tem um som<br /><em>na cabeça?</em></h2><p>Escolha uma frequência, salve a referência e manda a ideia. O próximo beat pode começar na sua mensagem.</p></div><a href={contactHref} className="radio-button purple-button">Mandar briefing <ArrowUpRight size={16} /></a></div></section>
      <section id="releases" className="releases-section reveal-section"><div className="radio-wrap"><div className="radio-section-head"><div><span className="section-no">03</span><h2>O que já<br /><em>saiu.</em></h2></div><p>Faixas produzidas para<br />artistas em movimento.</p></div><div className="release-list">{releases.map(release => <a key={release.title} href="https://open.spotify.com/" target="_blank" rel="noreferrer" className="release-row"><span className={`release-disc ${release.color}`}><Disc3 size={28} /></span><span><b>{release.title}</b><small>{release.artist} · {release.role}</small></span><span className="release-year">{release.year}</span><ArrowUpRight size={17} /></a>)}</div></div></section>
      <section id="about" className="radio-about radio-wrap reveal-section"><div className="about-copy-radio"><span className="section-no">04</span><h2>O beat abre<br />a conversa.</h2><p>João Alvarez cria beats e músicas com grave, textura e espaço para a voz aparecer. A rádio é o arquivo vivo desse processo: toda vez que entra uma prévia nova, uma nova porta se abre.</p></div><div className="about-stats"><div><b>beats</b><strong>04</strong></div><div><b>estilos</b><strong>06</strong></div><div><b>sessão</b><strong>24/7</strong></div></div></section>
      <section id="contact" className="radio-contact radio-wrap reveal-section"><div><span className="live-dot" /><span>se ouviu até aqui, talvez seja seu som.</span></div><h2>Ouviu algo<br />que parece <em>seu?</em></h2><a className="radio-button purple-button" href={contactHref}><Mail size={16} /> falar com J.A <ArrowUpRight size={16} /></a></section>
    </main>
    <footer className="radio-footer radio-wrap"><span><span className="ja-stamp small-stamp">J.A</span> João Alvarez / 2024</span><span className="footer-socials"><a href="https://instagram.com" target="_blank" rel="noreferrer" aria-label="Instagram"><Instagram size={15} strokeWidth={1.8} /></a><a href="https://open.spotify.com" target="_blank" rel="noreferrer" aria-label="Spotify"><Music2 size={15} strokeWidth={1.8} /></a><span>sinal aberto</span></span></footer>
    <nav className="mobile-tabbar" aria-label="Navegação rápida"><a href="#top"><House size={16} strokeWidth={1.8} /><span>início</span></a><a href="/catalogo"><AudioLines size={16} strokeWidth={1.8} /><span>catálogo</span></a><a href="#releases"><Disc3 size={16} strokeWidth={1.8} /><span>lançamentos</span></a><a href="#contact"><Mail size={16} strokeWidth={1.8} /><span>contato</span></a></nav>
    {activeBeat && <div className="radio-player"><div className="player-progress-radio" style={{ transform: `scaleX(${progress})` }} /><div className="radio-player-inner"><Cover beat={activeBeat} /><button className="player-main-button" onClick={() => void playBeat(activeBeat)} aria-label={playing ? "Pausar" : "Reproduzir"}>{playing ? <Pause size={16} fill="currentColor" /> : <Play size={16} fill="currentColor" />}</button><div className="player-name"><span>{playing ? "reproduzindo agora" : "prévia selecionada"}</span><b>{activeBeat.title}</b></div><Bars active={playing} /><button className={`player-share ${shared ? "shared" : ""}`} onClick={() => void shareBeat()} aria-label="Compartilhar beat">{shared ? "copiado" : <Share2 size={15} />}</button><a href={contactHref} className="player-contact">quero esse beat <ArrowUpRight size={14} /></a><button className="player-close" onClick={() => { audioRef.current?.pause(); setPlaying(false); }} aria-label="Parar prévia"><X size={17} /></button></div></div>}
  </div>;
}
